# See https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main
  repo: danielmoessner/online-kreditshop.de

# See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

# See https://www.netlifycms.org/docs/configuration-options/#locale
locale: de

# See https://www.netlifycms.org/docs/configuration-options/#display-url
display_url: https://online-kreditshop.de

# See https://www.netlifycms.org/docs/configuration-options/#site-url
site_url: https://online-kreditshop.de

# See https://www.netlifycms.org/docs/configuration-options/#media-folder
media_folder: /content/media

# See https://www.netlifycms.org/docs/configuration-options/#public-folder
public_folder: ../media

# See https://www.netlifycms.org/docs/collection-types/
collections:
  - name: page
    label: Seiten
    label_singular: Seite
    delete: false
    editor:
      preview: false
    files:
      - file: content/pages/home.yml
        label: Startseite
        name: home
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: home }
          - label: 'Meta'
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }

      - file: content/pages/mortgage.md
        label: Baufinanzierung
        name: mortgage
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: mortgage }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }
          - { label: Titel, name: title, widget: string }
          - { label: Kategorie, name: category, widget: string }
          - { label: Kurzbeschreibung, name: shortDescription, widget: text }
          - { label: Text, name: body, widget: markdown }

      - file: content/pages/articles.yml
        label: Ratgeber
        name: articles
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: articles }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: string }
          - label: Artikel
            name: articles
            widget: object
            fields:
              - { label: Lesen Button, name: button, widget: string }

      - file: content/pages/contact.yml
        label: Kontakt
        name: contact
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: page }
          - { label: Slug, name: slug, widget: hidden, default: contact }
          - label: Meta
            name: meta
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - label: Beschreibung
                name: description
                widget: text
              - { label: Bild, name: image, widget: image }
          - label: Header
            name: header
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: string }
          - label: Kontakt
            name: contact
            widget: object
            fields:
              - { label: Titel, name: title, widget: string }
              - { label: Text, name: text, widget: text }
              - { label: Maps, name: maps, widget: string }

  - name: article
    label: Ratgeber
    label_singular: Ratgeber
    editor:
      preview: true
    folder: content/article
    slug: '{{fields.slug}}'
    create: true
    preview_path: ratgeber/{{fields.slug}}/
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: article }
      - { label: Titel, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Datum, name: date, widget: datetime, date_format: DD.MM.YYYY, time_format: '' }
      - { label: Kategorie, name: category, widget: string }
      - { label: Kurzbeschreibung, name: shortDescription, widget: text }
      - { label: Inhalt, name: body, widget: markdown }

  - name: category
    label: Kategorien
    label_singular: Kategorie
    editor:
      preview: false
    folder: content/categories
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Sammlung, name: collection, widget: hidden, default: category }
      - { label: Titel, name: title, widget: string }

  - name: 'setting'
    label: Einstellungen
    label_singular: Einstellung
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: Global
        name: 'global-settings'
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: global }
          - { label: Favicon, name: favicon, widget: image }
          - { label: Logo, name: logo, widget: image }
      - file: content/settings/teaser.yml
        label: Teaser
        name: teaser
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: teaser }
          - { label: Text, name: text, widget: text }
          - { label: Button Text, name: buttonText, widget: string }
          - { label: Button Link, name: buttonLink, widget: string }
      - file: content/settings/contact.yml
        label: Kontaktinformationen
        name: contact
        preview: false
        fields:
          - { label: Sammlung, name: collection, widget: hidden, default: setting }
          - { label: Slug, name: slug, widget: hidden, default: contact }
          - { label: Telefonnummer, name: phone, widget: string }
          - { label: E-Mail, name: email, widget: string }
          - { label: Adresse, name: address, widget: text }
